CREATE TABLE `intakeForms` (
	`id` int AUTO_INCREMENT NOT NULL,
	`primaryName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50),
	`preferredLanguage` varchar(50) NOT NULL DEFAULT 'English',
	`whoRelocating` json NOT NULL,
	`partnerName` varchar(255),
	`partnerNationality` varchar(100),
	`partnerLanguages` text,
	`children` json,
	`pets` json,
	`fromCity` varchar(255) NOT NULL,
	`nationalities` text,
	`moveReasons` json NOT NULL,
	`arrivalDate` varchar(20),
	`dateFirmness` varchar(100),
	`intendedDuration` json,
	`targetCity` json NOT NULL,
	`livedInItalyBefore` varchar(100),
	`previousCountries` text,
	`rentOrBuy` json NOT NULL,
	`budget` json NOT NULL,
	`bedrooms` varchar(50),
	`propertyType` varchar(100),
	`propertyRequirements` json,
	`neighbourhoodVibe` json,
	`neighbourhoodInterest` text,
	`previousHomeNotes` text,
	`childEduProfiles` json,
	`italianImmersionScale` int,
	`curriculumPreference` json,
	`midYearEntry` json,
	`learningNeeds` text,
	`universityTarget` text,
	`professionalSituation` json,
	`partnerProfSituation` json,
	`flatTaxInterest` json,
	`livedInItalyLast9` json,
	`hasCommercialista` json,
	`bankingNeeds` json,
	`lifestyleDescriptors` json,
	`hobbies` text,
	`socialNetworkScale` int,
	`italianLevelYou` varchar(50),
	`italianLevelPartner` varchar(50),
	`healthcareNeeds` json,
	`healthcareOther` text,
	`dietaryNotes` text,
	`topPriorities` json,
	`biggestAnxiety` text,
	`prevReloScale` int,
	`prevReloWentWrong` text,
	`commsPref` json,
	`timezone` varchar(100),
	`additionalDecisionMaker` varchar(255),
	`anythingElse` text,
	`heardAboutDomus` json,
	`submittedAt` timestamp NOT NULL DEFAULT (now()),
	`advisorBriefSent` tinyint NOT NULL DEFAULT 0,
	`clientPreviewSent` tinyint NOT NULL DEFAULT 0,
	`assignedAdvisor` varchar(255),
	`internalNotes` text,
	CONSTRAINT `intakeForms_id` PRIMARY KEY(`id`)
);
